# The URL the site will be built for
base_url = "https://stories.univ.ai"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "tale-zola"

mothership_title = "Univ.AI"
mothership_url = "https://univ.ai"

title = "Stories"
description = "Bite sized stories on Data Science and AI"

taxonomies = [
  {name = "topics"},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
katex  =  true
author = "Rahul Dave"
company = "Univ.AI"

# Menu items


[[extra.menu]]
name = "Topics"
url = "topics"

[[extra.menu]]
name = "About"
url = "about"

[extra.footer]
start_year = "2021"  # start year of the site
end_year = "2021"    # end year of the site
info = ""

